name: SonarQube

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

env:
  sonarqube: ${{ secrets.SONAR_TOKEN }} 

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests with coverage
        run: |
          dotnet test --configuration Release --collect:"XPlat Code Coverage" \
            --results-directory ./TestResults

      - name: Generate Coverage Report
        run: |
          /usr/bin/mkdir -p coverage-reports
          dotnet tool install --global dotnet-reportgenerator-globaltool
          export PATH="$PATH:/home/runner/.dotnet/tools"
          reportgenerator \
            -reports:TestResults/**/*.xml \
            -targetdir:coverage-reports \
            -reporttypes:SonarQube

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ env.sonarqube }} 
        with:
          args: >
            -Dsonar.projectKey=ReinoutWW_HAN-CourseGenerator
            -Dsonar.organization=your-organization-key
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.cs.opencover.reportsPaths=coverage-reports/SonarQube.xml
