on:
  push:
    branches:
      - master
      - 'releases/**'
  pull_request:
    types: [opened, synchronize, reopened]

name: Main Workflow

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Install DotCover Tool
      run: dotnet tool install --global JetBrains.dotCover.GlobalTool

    - name: SonarQube Begin Analysis
      run: |
        dotnet sonarscanner begin /k:"ReinoutWW_HAN-CourseGenerator" \
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
          /d:sonar.cs.dotcover.reportsPaths="dotCover.Output.html"

    - name: Build Solution
      run: dotnet build --no-incremental

    - name: Run Tests with DotCover
      run: dotnet dotcover test --dcReportType=HTML

    - name: SonarQube End Analysis
      run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

    - name: Upload Coverage Report (Optional)
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: dotCover.Output.html
