name: SonarQube

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests with coverage
        run: |
          dotnet test --configuration Release --collect:"XPlat Code Coverage" \
            --results-directory ./TestResults
        continue-on-error: false

      - name: Convert coverage to SonarQube format
        run: |
          mkdir -p coverage-reports
          dotnet tool install --global dotnet-reportgenerator-globaltool
          reportgenerator \
            -reports:TestResults/**/*.xml \
            -targetdir:coverage-reports \
            -reporttypes:SonarQube
        env:
          PATH: ${{ runner.tool_cache }}/.store:$PATH

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.cs.opencover.reportsPaths=coverage-reports/SonarQube.xml
