name: Run Unit Tests

on:
  workflow_run:
    workflows:
      - Build Solution
    types:
      - completed

jobs:
  unit-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run HAN.Tests
        run: dotnet test HAN.Tests/HAN.Tests.csproj --no-build --verbosity normal --configuration Release
